package com.quickbooks.dto.purchase;

public class NextBillNumberResponse {

    private String billNumber;
    private boolean autoGenerated;

    public NextBillNumberResponse(String billNumber, boolean autoGenerated) {
        this.billNumber = billNumber;
        this.autoGenerated = autoGenerated;
    }

    public String getBillNumber() { return billNumber; }
    public void setBillNumber(String billNumber) { this.billNumber = billNumber; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }
}
