package com.quickbooks.dto.sale;

public class NextInvoiceNumberResponse {

    private String invoiceNumber;
    private boolean autoGenerated;

    public NextInvoiceNumberResponse(String invoiceNumber, boolean autoGenerated) {
        this.invoiceNumber = invoiceNumber;
        this.autoGenerated = autoGenerated;
    }

    public String getInvoiceNumber() { return invoiceNumber; }
    public void setInvoiceNumber(String invoiceNumber) { this.invoiceNumber = invoiceNumber; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }
}
